language: cpp

sudo: required
dist: xenial

branches:
  only:
    - master

env:
  global:
    - QT_VER=5.12.3

git:
  depth: 175


install: .travis/install.sh
script: .travis/script.sh

jobs:
  include:

# LINUX build
    - os: linux
      env: TARGET=x11-static

# OSX build
    - os: osx
      env: TARGET=macos-static
      compiler: clang
      before_install:
        - brew update
      install:
        - brew install qt5
        - brew link --force qt5
        - qmake -v
      script:
        - mkdir build && cd build
        - qmake ..
        - make check
      after_success:
        - export SUFFIX=$(git describe --always)_${TARGET}
        - zip -j fvi-launcher_${SUFFIX}.zip
          /opt/fvi-launcher/fvi-launcher
          ../README.md
          ../LICENSE.md
        - curl --upload-file
          fvi-launcher_${SUFFIX}.zip
          https://file.io/fvi-launcher_${SUFFIX}.zip
        - wget -c https://github.com/warfork/uploadtool/raw/master/upload.sh
        - bash ./upload.sh fvi-launcher_${SUFFIX}.zip
      deploy: null

services:
  - xvfb
